//This file is generated by an external tool, and should not be manually edited.
var PupList = new Array(2);

    PupList[0] = new Pup("Sophie",
                     "7",
                     "Cocker Spaniel",
                     "Female",
                     "Small",
                     "N/A",
                     "Snarky, small, superfluff."
    );

    PupList[1] = new Pup("Capt. Waffles",
                     "0",
                     "Avenger",
                     "Male",
                     "Hulk",
                     "N/A",
                     "I understood that reference."
    );
    